version: "3"

services:
    postgres_db:
        image: postgres:12.0-alpine
        volumes:
          - ./postgres_data_dev:/var/lib/postgresql/data/
        container_name: postgres
        restart: always
        environment:
          POSTGRES_USER: "dayfly"
          POSTGRES_PASSWORD: "dayfly"
          POSTGRES_DB: "dayfly_db"
        ports:
          - 5432:5432  
    react-app:
        #dockerfile 위치
        build: ./Frontend
            
        ports:
            - "3000:3000"
        #호스트와 컨테이너 동기화할곳
        volumes: 
            - ./Frontend:/app
            - build_folder:/app/build
            - ./Frontend/node_modules/:/app/node_modules
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true

    flask-app:
        build:  ./Backend

        ports:
            - "5000:5000"
        restart: always
        volumes:
            - ./Backend/web:/app   
        env_file: 
            - ./settings/dev/.env.dev  
        depends_on: 
            - postgres_db


volumes:
    postgres_data_dev:
    build_folder:
                


