version: "3"

services:
    react-app:
        build: ./Frontend
        volumes: 
            - ./Frontend:/app
            - build_folder:/app/build
            - ./Frontend/node_modules/:/app/node_modules
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true

    flask-app:
        build:  ./Backend
        ports:
            - "5000:5000"
        restart: always
        volumes:
            - ./Backend:/app   
        env_file: 
            - ./settings/prod/.env.prod 
        command: gunicorn -w 4 --bind 0.0.0.0:5000 --timeout=6000 --log-level=debug run:app

    
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        restart: "on-failure"
        volumes: 
            # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - build_folder:/var/www/Frontend
        depends_on:
            - flask-app
            - react-app

volumes:
    build_folder:

                


