version: "3"

services:
    # postgres_db:
    #     image: postgres:12.0-alpine
    #     volumes:
    #       - postgres_data:/var/lib/postgresql/data/
    #     container_name: postgres
    #     restart: always
    #     environment:
    #       POSTGRES_USER: "eg_user"
    #       POSTGRES_PASSWORD: "eg_pw"
    #       POSTGRES_DB: "eg_dv"
    #     ports:
    #       - 5432:5432  
    flask-app:
        build:  ./Backend
        command: python3 app.py run -h 0.0.0.0
        expose:
            - 5000
        ports:
            - "5000:5000"
        restart: always
        volumes:
            - ./Backend/web:/app   
        env_file: 
            - ./settings/dev/.env.dev  
        # depends_on: 
        #     - postgres_db
    react-app:
        build: ./Frontend
        command: ["npm","start"]
        ports:
            - "3000:3000"
        volumes: 
            - ./Frontend:/app
            - ./Frontend/node_modules/:/app/node_modules
        stdin_open: true
        tty: true

        environment:
            - CHOKIDAR_USEPOLLING=true


# volumes:
#     postgres_data:
                


